### ISSUE TITLE
Stepwise logistic regression model selection based on Chi Square Test 

### ISSUE THREAD

**Issue by aaronxs** [rsquaredacademy/blorr#45]
Hi,

I was wondering would it be possible to create a function that does model selection based on p values (like **ols_step_both_p** from the **olsrr** package). Specifically p values from ANOVA/Chi Square Test similar to the STEPWISE procedure in SAS (https://support.sas.com/documentation/cdl/en/statug/63033/HTML/default/viewer.htm#statug_logistic_sect029.htm)

Thank you!
Aaron

**Comment by aravindhebbali** [comment]
Check out the below examples;

- https://blorr.rsquaredacademy.com/reference/blr_step_p_forward.html
- https://blorr.rsquaredacademy.com/reference/blr_step_p_backward.html
- https://blorr.rsquaredacademy.com/reference/blr_step_p_both.html

**Comment by aravindhebbali** [comment]
Need to use `MASS::Anova()` to select variables based on p-values from Wald chi square test.

**Comment by aaronxs** [comment]
It works perfectly! Thank you so much!!

Another question: is there any ways you can make it so that the final model is saved in **Value**? Thanks!
