### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by sagarneelde** [rsquaredacademy/blorr#60]
Hi,
I failed to install the package from CRAN/Github. Here are the few errors I found:

1. Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :  there is no package called 'rio'
Installed rio and tried again

2. Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called 'carData'
Installed carData and tried again

3. Error : .onLoad failed in loadNamespace() for 'checkmate', details:
  call: NULL
  error: 'import' is not an exported object from 'namespace:backports'
ERROR: lazy loading failed for package 'blorr'

What shall I do now?

> sessionInfo() # For Reference
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      R6_2.2.2        tools_3.3.3     withr_2.1.1     curl_3.1        memoise_1.0.0  
 [7] knitr_1.19      git2r_0.18.0    digest_0.6.12   devtools_1.12.0

**Comment by aravindhebbali** [comment]
@sagarneelde Were you able to install the `blorr` package?

**Comment by sagarneelde** [comment]
@aravindhebbali 
I installed backports and checkmate without any issues and the following issue cropped up while installing blorr
`Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'httpuv' 1.3.3 is being loaded, but >= 1.3.5 is required`

So I installed httpuv. It took me ages! But it worked finally. Thank you very much @aravindhebbali

**Comment by aravindhebbali** [comment]
Thanks @sagarneelde for reporting the installation issues. I will add the specific versions of the package dependencies in the DESCRIPTION file.
